const message0 = {
  code: 551,
  earthquake: {
    domesticTsunami: 'None',
    foreignTsunami: 'Unknown',
    hypocenter: {
      depth: 10,
      latitude: 32.6,
      longitude: 130.7,
      magnitude: 3.5,
      name: '熊本県熊本地方',
    },
    maxScale: 30,
    time: '2024/08/10 14:18:00',
  },
  id: '66b6f8d8d616be440743d3bf',
  issue: {
    correct: 'None',
    source: '気象庁',
    time: '2024/08/10 14:21:28',
    type: 'DetailScale',
  },
  points: [
    {
      addr: '宇城市豊野町',
      isArea: false,
      pref: '熊本県',
      scale: 30,
    },
    {
      addr: '宇城市松橋町',
      isArea: false,
      pref: '熊本県',
      scale: 20,
    },
    {
      addr: '宇城市不知火町',
      isArea: false,
      pref: '熊本県',
      scale: 20,
    },
    {
      addr: '宇城市小川町',
      isArea: false,
      pref: '熊本県',
      scale: 20,
    },
    {
      addr: '熊本西区春日',
      isArea: false,
      pref: '熊本県',
      scale: 20,
    },
    {
      addr: '熊本南区富合町',
      isArea: false,
      pref: '熊本県',
      scale: 20,
    },
    {
      addr: '熊本南区城南町',
      isArea: false,
      pref: '熊本県',
      scale: 20,
    },
    {
      addr: '八代市千丁町',
      isArea: false,
      pref: '熊本県',
      scale: 20,
    },
    {
      addr: '八代市鏡町',
      isArea: false,
      pref: '熊本県',
      scale: 20,
    },
    {
      addr: '八代市泉支所',
      isArea: false,
      pref: '熊本県',
      scale: 20,
    },
    {
      addr: '八代市平山新町',
      isArea: false,
      pref: '熊本県',
      scale: 10,
    },
    {
      addr: '八代市泉町',
      isArea: false,
      pref: '熊本県',
      scale: 10,
    },
    {
      addr: '八代市新地町',
      isArea: false,
      pref: '熊本県',
      scale: 10,
    },
    {
      addr: '八代市東陽町',
      isArea: false,
      pref: '熊本県',
      scale: 10,
    },
    {
      addr: '八代市坂本町',
      isArea: false,
      pref: '熊本県',
      scale: 10,
    },
    {
      addr: '宇土市浦田町',
      isArea: false,
      pref: '熊本県',
      scale: 20,
    },
    {
      addr: '熊本美里町馬場',
      isArea: false,
      pref: '熊本県',
      scale: 20,
    },
    {
      addr: '熊本美里町永富',
      isArea: false,
      pref: '熊本県',
      scale: 10,
    },
    {
      addr: '西原村小森',
      isArea: false,
      pref: '熊本県',
      scale: 20,
    },
    {
      addr: '御船町御船',
      isArea: false,
      pref: '熊本県',
      scale: 20,
    },
    {
      addr: '嘉島町上島',
      isArea: false,
      pref: '熊本県',
      scale: 20,
    },
    {
      addr: '甲佐町豊内',
      isArea: false,
      pref: '熊本県',
      scale: 20,
    },
    {
      addr: '氷川町島地',
      isArea: false,
      pref: '熊本県',
      scale: 20,
    },
    {
      addr: '氷川町宮原',
      isArea: false,
      pref: '熊本県',
      scale: 10,
    },
    {
      addr: '熊本中央区大江',
      isArea: false,
      pref: '熊本県',
      scale: 10,
    },
    {
      addr: '熊本東区佐土原',
      isArea: false,
      pref: '熊本県',
      scale: 10,
    },
    {
      addr: '熊本北区植木町',
      isArea: false,
      pref: '熊本県',
      scale: 10,
    },
    {
      addr: '菊池市旭志',
      isArea: false,
      pref: '熊本県',
      scale: 10,
    },
    {
      addr: '大津町大津',
      isArea: false,
      pref: '熊本県',
      scale: 10,
    },
    {
      addr: '益城町宮園',
      isArea: false,
      pref: '熊本県',
      scale: 10,
    },
    {
      addr: '山都町浜町',
      isArea: false,
      pref: '熊本県',
      scale: 10,
    },
    {
      addr: '熊本高森町高森',
      isArea: false,
      pref: '熊本県',
      scale: 10,
    },
    {
      addr: '五木村甲',
      isArea: false,
      pref: '熊本県',
      scale: 10,
    },
    {
      addr: '上天草市大矢野町',
      isArea: false,
      pref: '熊本県',
      scale: 10,
    },
    {
      addr: '上天草市松島町',
      isArea: false,
      pref: '熊本県',
      scale: 10,
    },
    {
      addr: '上天草市姫戸町',
      isArea: false,
      pref: '熊本県',
      scale: 10,
    },
    {
      addr: '大牟田市昭和町',
      isArea: false,
      pref: '福岡県',
      scale: 10,
    },
    {
      addr: '雲仙市小浜町雲仙',
      isArea: false,
      pref: '長崎県',
      scale: 10,
    },
    {
      addr: '雲仙市雲仙出張所',
      isArea: false,
      pref: '長崎県',
      scale: 10,
    },
    {
      addr: '南島原市北有馬町',
      isArea: false,
      pref: '長崎県',
      scale: 10,
    },
    {
      addr: '延岡市北方町総合支所',
      isArea: false,
      pref: '宮崎県',
      scale: 10,
    },
    {
      addr: '椎葉村総合運動公園',
      isArea: false,
      pref: '宮崎県',
      scale: 10,
    },
    {
      addr: '椎葉村下福良',
      isArea: false,
      pref: '宮崎県',
      scale: 10,
    },
    {
      addr: '宮崎美郷町田代',
      isArea: false,
      pref: '宮崎県',
      scale: 10,
    },
    {
      addr: '高千穂町三田井',
      isArea: false,
      pref: '宮崎県',
      scale: 10,
    },
  ],
  time: '2024/08/10 14:21:28.898',
  timestamp: {
    convert: '2024/08/10 14:21:28.895',
    register: '2024/08/10 14:21:28.899',
  },
  user_agent: 'jmaxml-seis-parser-go, relay, register-api',
  ver: '20231023',
};

const message1 = {
  code: 551,
  earthquake: {
    domesticTsunami: 'None',
    foreignTsunami: 'Unknown',
    hypocenter: {
      depth: 490,
      latitude: 47.4,
      longitude: 145.6,
      magnitude: 6.8,
      name: 'オホーツク海南部',
    },
    maxScale: 30,
    time: '2024/08/10 12:29:00',
  },
  id: '66b6dfd8d616be440743d3bc',
  issue: {
    correct: 'None',
    source: '気象庁',
    time: '2024/08/10 12:34:47',
    type: 'DetailScale',
  },
  points: [
    {
      addr: '函館市新浜町',
      isArea: false,
      pref: '北海道',
      scale: 30,
    },
    {
      addr: '函館市泊町',
      isArea: false,
      pref: '北海道',
      scale: 20,
    },
    {
      addr: '函館市尾札部町',
      isArea: false,
      pref: '北海道',
      scale: 10,
    },
    {
      addr: '函館市美原',
      isArea: false,
      pref: '北海道',
      scale: 10,
    },
    {
      addr: '函館市川汲町',
      isArea: false,
      pref: '北海道',
      scale: 10,
    },
    {
      addr: '函館市日ノ浜町',
      isArea: false,
      pref: '北海道',
      scale: 10,
    },
    {
      addr: '七飯町桜町',
      isArea: false,
      pref: '北海道',
      scale: 10,
    },
    {
      addr: '七飯町本町',
      isArea: false,
      pref: '北海道',
      scale: 10,
    },
    {
      addr: '鹿部町宮浜',
      isArea: false,
      pref: '北海道',
      scale: 10,
    },
    {
      addr: '新篠津村第４７線',
      isArea: false,
      pref: '北海道',
      scale: 20,
    },
    {
      addr: '千歳市支笏湖温泉',
      isArea: false,
      pref: '北海道',
      scale: 20,
    },
    {
      addr: '千歳市北栄',
      isArea: false,
      pref: '北海道',
      scale: 10,
    },
    {
      addr: '新千歳空港',
      isArea: false,
      pref: '北海道',
      scale: 10,
    },
    {
      addr: '千歳市若草',
      isArea: false,
      pref: '北海道',
      scale: 10,
    },
    {
      addr: '北広島市中の沢',
      isArea: false,
      pref: '北海道',
      scale: 10,
    },
    {
      addr: '上ノ国町大留',
      isArea: false,
      pref: '北海道',
      scale: 20,
    },
    {
      addr: '檜山江差町姥神',
      isArea: false,
      pref: '北海道',
      scale: 10,
    },
    {
      addr: '檜山江差町中歌町',
      isArea: false,
      pref: '北海道',
      scale: 10,
    },
    {
      addr: '厚沢部町新町',
      isArea: false,
      pref: '北海道',
      scale: 10,
    },
    {
      addr: '猿払村浅茅野',
      isArea: false,
      pref: '北海道',
      scale: 20,
    },
    {
      addr: '稚内市恵北',
      isArea: false,
      pref: '北海道',
      scale: 10,
    },
    {
      addr: '稚内市開運',
      isArea: false,
      pref: '北海道',
      scale: 10,
    },
    {
      addr: '稚内市沼川',
      isArea: false,
      pref: '北海道',
      scale: 10,
    },
    {
      addr: '豊富町西６条',
      isArea: false,
      pref: '北海道',
      scale: 10,
    },
    {
      addr: '室蘭市寿町',
      isArea: false,
      pref: '北海道',
      scale: 20,
    },
    {
      addr: '苫小牧市末広町',
      isArea: false,
      pref: '北海道',
      scale: 20,
    },
    {
      addr: '厚真町鹿沼',
      isArea: false,
      pref: '北海道',
      scale: 20,
    },
    {
      addr: '厚真町京町',
      isArea: false,
      pref: '北海道',
      scale: 10,
    },
    {
      addr: 'むかわ町松風',
      isArea: false,
      pref: '北海道',
      scale: 20,
    },
    {
      addr: 'むかわ町穂別',
      isArea: false,
      pref: '北海道',
      scale: 20,
    },
    {
      addr: '登別市桜木町',
      isArea: false,
      pref: '北海道',
      scale: 10,
    },
    {
      addr: '白老町竹浦',
      isArea: false,
      pref: '北海道',
      scale: 10,
    },
    {
      addr: '白老町緑丘',
      isArea: false,
      pref: '北海道',
      scale: 10,
    },
    {
      addr: '安平町追分柏が丘',
      isArea: false,
      pref: '北海道',
      scale: 10,
    },
    {
      addr: '新冠町北星町',
      isArea: false,
      pref: '北海道',
      scale: 20,
    },
    {
      addr: '新ひだか町静内山手町',
      isArea: false,
      pref: '北海道',
      scale: 20,
    },
    {
      addr: '新ひだか町静内御幸町',
      isArea: false,
      pref: '北海道',
      scale: 20,
    },
    {
      addr: '新ひだか町三石旭町',
      isArea: false,
      pref: '北海道',
      scale: 20,
    },
    {
      addr: '新ひだか町静内御園',
      isArea: false,
      pref: '北海道',
      scale: 10,
    },
    {
      addr: '浦河町野深',
      isArea: false,
      pref: '北海道',
      scale: 20,
    },
    {
      addr: '浦河町潮見',
      isArea: false,
      pref: '北海道',
      scale: 20,
    },
    {
      addr: '浦河町築地',
      isArea: false,
      pref: '北海道',
      scale: 20,
    },
    {
      addr: '様似町栄町',
      isArea: false,
      pref: '北海道',
      scale: 20,
    },
    {
      addr: 'えりも町目黒',
      isArea: false,
      pref: '北海道',
      scale: 10,
    },
    {
      addr: 'えりも町えりも岬',
      isArea: false,
      pref: '北海道',
      scale: 10,
    },
    {
      addr: '浦幌町桜町',
      isArea: false,
      pref: '北海道',
      scale: 20,
    },
    {
      addr: '帯広市東６条',
      isArea: false,
      pref: '北海道',
      scale: 10,
    },
    {
      addr: '十勝清水町南４条',
      isArea: false,
      pref: '北海道',
      scale: 10,
    },
    {
      addr: '幕別町忠類錦町',
      isArea: false,
      pref: '北海道',
      scale: 10,
    },
    {
      addr: '豊頃町茂岩本町',
      isArea: false,
      pref: '北海道',
      scale: 10,
    },
    {
      addr: '本別町北２丁目',
      isArea: false,
      pref: '北海道',
      scale: 10,
    },
    {
      addr: '釧路市幸町',
      isArea: false,
      pref: '北海道',
      scale: 20,
    },
    {
      addr: '釧路市黒金町',
      isArea: false,
      pref: '北海道',
      scale: 20,
    },
    {
      addr: '釧路市音別町中園',
      isArea: false,
      pref: '北海道',
      scale: 20,
    },
    {
      addr: '釧路市阿寒町中央',
      isArea: false,
      pref: '北海道',
      scale: 10,
    },
    {
      addr: '釧路町別保',
      isArea: false,
      pref: '北海道',
      scale: 20,
    },
    {
      addr: '厚岸町真栄',
      isArea: false,
      pref: '北海道',
      scale: 20,
    },
    {
      addr: '厚岸町尾幌',
      isArea: false,
      pref: '北海道',
      scale: 10,
    },
    {
      addr: '浜中町茶内',
      isArea: false,
      pref: '北海道',
      scale: 20,
    },
    {
      addr: '浜中町湯沸',
      isArea: false,
      pref: '北海道',
      scale: 10,
    },
    {
      addr: '標茶町塘路',
      isArea: false,
      pref: '北海道',
      scale: 20,
    },
    {
      addr: '標茶町川上',
      isArea: false,
      pref: '北海道',
      scale: 10,
    },
    {
      addr: '白糠町西１条',
      isArea: false,
      pref: '北海道',
      scale: 20,
    },
    {
      addr: '鶴居村鶴居東',
      isArea: false,
      pref: '北海道',
      scale: 10,
    },
    {
      addr: '別海町常盤',
      isArea: false,
      pref: '北海道',
      scale: 20,
    },
    {
      addr: '別海町本別海',
      isArea: false,
      pref: '北海道',
      scale: 20,
    },
    {
      addr: '根室市牧の内',
      isArea: false,
      pref: '北海道',
      scale: 20,
    },
    {
      addr: '根室市厚床',
      isArea: false,
      pref: '北海道',
      scale: 20,
    },
    {
      addr: '根室市落石東',
      isArea: false,
      pref: '北海道',
      scale: 20,
    },
    {
      addr: '根室市珸瑤瑁',
      isArea: false,
      pref: '北海道',
      scale: 20,
    },
    {
      addr: '根室市弥栄',
      isArea: false,
      pref: '北海道',
      scale: 10,
    },
    {
      addr: '根室市豊里',
      isArea: false,
      pref: '北海道',
      scale: 10,
    },
    {
      addr: '札幌中央区北２条',
      isArea: false,
      pref: '北海道',
      scale: 10,
    },
    {
      addr: '札幌中央区南４条',
      isArea: false,
      pref: '北海道',
      scale: 10,
    },
    {
      addr: '札幌北区篠路',
      isArea: false,
      pref: '北海道',
      scale: 10,
    },
    {
      addr: '札幌北区新琴似',
      isArea: false,
      pref: '北海道',
      scale: 10,
    },
    {
      addr: '札幌東区元町',
      isArea: false,
      pref: '北海道',
      scale: 10,
    },
    {
      addr: '札幌西区琴似',
      isArea: false,
      pref: '北海道',
      scale: 10,
    },
    {
      addr: '札幌手稲区前田',
      isArea: false,
      pref: '北海道',
      scale: 10,
    },
    {
      addr: '江別市緑町',
      isArea: false,
      pref: '北海道',
      scale: 10,
    },
    {
      addr: '木古内町木古内',
      isArea: false,
      pref: '北海道',
      scale: 10,
    },
    {
      addr: '胆振伊達市大滝区本町',
      isArea: false,
      pref: '北海道',
      scale: 10,
    },
    {
      addr: '日高地方日高町門別',
      isArea: false,
      pref: '北海道',
      scale: 10,
    },
    {
      addr: '平取町本町',
      isArea: false,
      pref: '北海道',
      scale: 10,
    },
    {
      addr: '平取町振内',
      isArea: false,
      pref: '北海道',
      scale: 10,
    },
    {
      addr: '新得町２条',
      isArea: false,
      pref: '北海道',
      scale: 10,
    },
    {
      addr: '中札内村東２条',
      isArea: false,
      pref: '北海道',
      scale: 10,
    },
    {
      addr: '十勝大樹町東本通',
      isArea: false,
      pref: '北海道',
      scale: 10,
    },
    {
      addr: '広尾町並木通',
      isArea: false,
      pref: '北海道',
      scale: 10,
    },
    {
      addr: '広尾町白樺通',
      isArea: false,
      pref: '北海道',
      scale: 10,
    },
    {
      addr: '標津町北２条',
      isArea: false,
      pref: '北海道',
      scale: 10,
    },
    {
      addr: '平内町小湊',
      isArea: false,
      pref: '青森県',
      scale: 30,
    },
    {
      addr: '平内町東田沢',
      isArea: false,
      pref: '青森県',
      scale: 20,
    },
    {
      addr: '青森市花園',
      isArea: false,
      pref: '青森県',
      scale: 20,
    },
    {
      addr: '青森市中央',
      isArea: false,
      pref: '青森県',
      scale: 10,
    },
    {
      addr: '青森市浪岡',
      isArea: false,
      pref: '青森県',
      scale: 10,
    },
    {
      addr: 'つがる市稲垣町',
      isArea: false,
      pref: '青森県',
      scale: 20,
    },
    {
      addr: 'つがる市柏',
      isArea: false,
      pref: '青森県',
      scale: 10,
    },
    {
      addr: 'つがる市森田町',
      isArea: false,
      pref: '青森県',
      scale: 10,
    },
    {
      addr: 'つがる市車力町',
      isArea: false,
      pref: '青森県',
      scale: 10,
    },
    {
      addr: 'つがる市木造',
      isArea: false,
      pref: '青森県',
      scale: 10,
    },
    {
      addr: '外ヶ浜町蟹田',
      isArea: false,
      pref: '青森県',
      scale: 20,
    },
    {
      addr: '外ヶ浜町平舘',
      isArea: false,
      pref: '青森県',
      scale: 10,
    },
    {
      addr: '五所川原市敷島町',
      isArea: false,
      pref: '青森県',
      scale: 10,
    },
    {
      addr: '五所川原市相内',
      isArea: false,
      pref: '青森県',
      scale: 10,
    },
    {
      addr: '五所川原市金木町',
      isArea: false,
      pref: '青森県',
      scale: 10,
    },
    {
      addr: '今別町今別',
      isArea: false,
      pref: '青森県',
      scale: 10,
    },
    {
      addr: '蓬田村蓬田',
      isArea: false,
      pref: '青森県',
      scale: 10,
    },
    {
      addr: '板柳町板柳',
      isArea: false,
      pref: '青森県',
      scale: 10,
    },
    {
      addr: '鶴田町鶴田',
      isArea: false,
      pref: '青森県',
      scale: 10,
    },
    {
      addr: '中泊町中里',
      isArea: false,
      pref: '青森県',
      scale: 10,
    },
    {
      addr: '八戸市南郷',
      isArea: false,
      pref: '青森県',
      scale: 30,
    },
    {
      addr: '八戸市湊町',
      isArea: false,
      pref: '青森県',
      scale: 20,
    },
    {
      addr: '八戸市内丸',
      isArea: false,
      pref: '青森県',
      scale: 20,
    },
    {
      addr: '八戸市島守',
      isArea: false,
      pref: '青森県',
      scale: 10,
    },
    {
      addr: '階上町道仏',
      isArea: false,
      pref: '青森県',
      scale: 30,
    },
    {
      addr: '十和田市西十二番町',
      isArea: false,
      pref: '青森県',
      scale: 20,
    },
    {
      addr: '十和田市西二番町',
      isArea: false,
      pref: '青森県',
      scale: 10,
    },
    {
      addr: '十和田市奥瀬',
      isArea: false,
      pref: '青森県',
      scale: 10,
    },
    {
      addr: '三沢市桜町',
      isArea: false,
      pref: '青森県',
      scale: 20,
    },
    {
      addr: '野辺地町田狭沢',
      isArea: false,
      pref: '青森県',
      scale: 20,
    },
    {
      addr: '七戸町森ノ上',
      isArea: false,
      pref: '青森県',
      scale: 20,
    },
    {
      addr: '七戸町七戸',
      isArea: false,
      pref: '青森県',
      scale: 20,
    },
    {
      addr: '六戸町犬落瀬',
      isArea: false,
      pref: '青森県',
      scale: 20,
    },
    {
      addr: '横浜町林ノ脇',
      isArea: false,
      pref: '青森県',
      scale: 20,
    },
    {
      addr: '横浜町寺下',
      isArea: false,
      pref: '青森県',
      scale: 20,
    },
    {
      addr: '東北町上北南',
      isArea: false,
      pref: '青森県',
      scale: 20,
    },
    {
      addr: '東北町塔ノ沢山',
      isArea: false,
      pref: '青森県',
      scale: 20,
    },
    {
      addr: '六ヶ所村尾駮',
      isArea: false,
      pref: '青森県',
      scale: 20,
    },
    {
      addr: '六ヶ所村出戸',
      isArea: false,
      pref: '青森県',
      scale: 10,
    },
    {
      addr: 'おいらせ町中下田',
      isArea: false,
      pref: '青森県',
      scale: 20,
    },
    {
      addr: 'おいらせ町上明堂',
      isArea: false,
      pref: '青森県',
      scale: 20,
    },
    {
      addr: '三戸町在府小路町',
      isArea: false,
      pref: '青森県',
      scale: 20,
    },
    {
      addr: '五戸町古舘',
      isArea: false,
      pref: '青森県',
      scale: 20,
    },
    {
      addr: '五戸町倉石中市',
      isArea: false,
      pref: '青森県',
      scale: 20,
    },
    {
      addr: '青森南部町苫米地',
      isArea: false,
      pref: '青森県',
      scale: 20,
    },
    {
      addr: '青森南部町平',
      isArea: false,
      pref: '青森県',
      scale: 20,
    },
    {
      addr: '青森南部町沖田面',
      isArea: false,
      pref: '青森県',
      scale: 10,
    },
    {
      addr: '田子町田子',
      isArea: false,
      pref: '青森県',
      scale: 10,
    },
    {
      addr: '新郷村戸来',
      isArea: false,
      pref: '青森県',
      scale: 10,
    },
    {
      addr: 'むつ市大畑町中島',
      isArea: false,
      pref: '青森県',
      scale: 30,
    },
    {
      addr: 'むつ市金曲',
      isArea: false,
      pref: '青森県',
      scale: 20,
    },
    {
      addr: 'むつ市川内町',
      isArea: false,
      pref: '青森県',
      scale: 20,
    },
    {
      addr: 'むつ市大畑町奥薬研',
      isArea: false,
      pref: '青森県',
      scale: 10,
    },
    {
      addr: 'むつ市脇野沢',
      isArea: false,
      pref: '青森県',
      scale: 10,
    },
    {
      addr: '東通村砂子又蒲谷地',
      isArea: false,
      pref: '青森県',
      scale: 20,
    },
    {
      addr: '東通村砂子又沢内',
      isArea: false,
      pref: '青森県',
      scale: 20,
    },
    {
      addr: '東通村尻屋',
      isArea: false,
      pref: '青森県',
      scale: 10,
    },
    {
      addr: '東通村白糠',
      isArea: false,
      pref: '青森県',
      scale: 10,
    },
    {
      addr: '大間町大間',
      isArea: false,
      pref: '青森県',
      scale: 10,
    },
    {
      addr: '風間浦村易国間',
      isArea: false,
      pref: '青森県',
      scale: 10,
    },
    {
      addr: '佐井村長後',
      isArea: false,
      pref: '青森県',
      scale: 10,
    },
    {
      addr: '佐井村佐井',
      isArea: false,
      pref: '青森県',
      scale: 10,
    },
    {
      addr: '藤崎町西豊田',
      isArea: false,
      pref: '青森県',
      scale: 20,
    },
    {
      addr: '藤崎町水木',
      isArea: false,
      pref: '青森県',
      scale: 10,
    },
    {
      addr: '弘前市弥生',
      isArea: false,
      pref: '青森県',
      scale: 10,
    },
    {
      addr: '弘前市賀田',
      isArea: false,
      pref: '青森県',
      scale: 10,
    },
    {
      addr: '黒石市市ノ町',
      isArea: false,
      pref: '青森県',
      scale: 10,
    },
    {
      addr: '平川市猿賀',
      isArea: false,
      pref: '青森県',
      scale: 10,
    },
    {
      addr: '平川市柏木町',
      isArea: false,
      pref: '青森県',
      scale: 10,
    },
    {
      addr: '西目屋村田代',
      isArea: false,
      pref: '青森県',
      scale: 10,
    },
    {
      addr: '大鰐町大鰐',
      isArea: false,
      pref: '青森県',
      scale: 10,
    },
    {
      addr: '田舎館村田舎館',
      isArea: false,
      pref: '青森県',
      scale: 10,
    },
    {
      addr: '盛岡市薮川',
      isArea: false,
      pref: '岩手県',
      scale: 30,
    },
    {
      addr: '盛岡市山王町',
      isArea: false,
      pref: '岩手県',
      scale: 20,
    },
    {
      addr: '盛岡市渋民',
      isArea: false,
      pref: '岩手県',
      scale: 20,
    },
    {
      addr: '盛岡市馬場町',
      isArea: false,
      pref: '岩手県',
      scale: 10,
    },
    {
      addr: '二戸市浄法寺町',
      isArea: false,
      pref: '岩手県',
      scale: 20,
    },
    {
      addr: '二戸市福岡',
      isArea: false,
      pref: '岩手県',
      scale: 10,
    },
    {
      addr: '二戸市石切所',
      isArea: false,
      pref: '岩手県',
      scale: 10,
    },
    {
      addr: '八幡平市田頭',
      isArea: false,
      pref: '岩手県',
      scale: 20,
    },
    {
      addr: '八幡平市野駄',
      isArea: false,
      pref: '岩手県',
      scale: 20,
    },
    {
      addr: '八幡平市大更',
      isArea: false,
      pref: '岩手県',
      scale: 10,
    },
    {
      addr: '八幡平市叺田',
      isArea: false,
      pref: '岩手県',
      scale: 10,
    },
    {
      addr: '滝沢市鵜飼',
      isArea: false,
      pref: '岩手県',
      scale: 20,
    },
    {
      addr: '岩手町五日市',
      isArea: false,
      pref: '岩手県',
      scale: 20,
    },
    {
      addr: '矢巾町南矢幅',
      isArea: false,
      pref: '岩手県',
      scale: 20,
    },
    {
      addr: '軽米町軽米',
      isArea: false,
      pref: '岩手県',
      scale: 20,
    },
    {
      addr: '一戸町高善寺',
      isArea: false,
      pref: '岩手県',
      scale: 20,
    },
    {
      addr: '雫石町千刈田',
      isArea: false,
      pref: '岩手県',
      scale: 10,
    },
    {
      addr: '葛巻町葛巻元木',
      isArea: false,
      pref: '岩手県',
      scale: 10,
    },
    {
      addr: '紫波町紫波中央駅前',
      isArea: false,
      pref: '岩手県',
      scale: 10,
    },
    {
      addr: '九戸村伊保内',
      isArea: false,
      pref: '岩手県',
      scale: 10,
    },
    {
      addr: '宮古市田老',
      isArea: false,
      pref: '岩手県',
      scale: 20,
    },
    {
      addr: '宮古市鍬ヶ崎',
      isArea: false,
      pref: '岩手県',
      scale: 10,
    },
    {
      addr: '宮古市五月町',
      isArea: false,
      pref: '岩手県',
      scale: 10,
    },
    {
      addr: '宮古市川井',
      isArea: false,
      pref: '岩手県',
      scale: 10,
    },
    {
      addr: '宮古市区界',
      isArea: false,
      pref: '岩手県',
      scale: 10,
    },
    {
      addr: '久慈市川崎町',
      isArea: false,
      pref: '岩手県',
      scale: 20,
    },
    {
      addr: '久慈市枝成沢',
      isArea: false,
      pref: '岩手県',
      scale: 20,
    },
    {
      addr: '久慈市長内町',
      isArea: false,
      pref: '岩手県',
      scale: 10,
    },
    {
      addr: '普代村銅屋',
      isArea: false,
      pref: '岩手県',
      scale: 20,
    },
    {
      addr: '野田村野田',
      isArea: false,
      pref: '岩手県',
      scale: 20,
    },
    {
      addr: '岩手洋野町種市',
      isArea: false,
      pref: '岩手県',
      scale: 20,
    },
    {
      addr: '岩手洋野町大野',
      isArea: false,
      pref: '岩手県',
      scale: 10,
    },
    {
      addr: '山田町八幡町',
      isArea: false,
      pref: '岩手県',
      scale: 10,
    },
    {
      addr: '山田町大沢',
      isArea: false,
      pref: '岩手県',
      scale: 10,
    },
    {
      addr: '岩泉町大川',
      isArea: false,
      pref: '岩手県',
      scale: 10,
    },
    {
      addr: '大船渡市大船渡町',
      isArea: false,
      pref: '岩手県',
      scale: 10,
    },
    {
      addr: '釜石市中妻町',
      isArea: false,
      pref: '岩手県',
      scale: 10,
    },
    {
      addr: '大槌町上町',
      isArea: false,
      pref: '岩手県',
      scale: 10,
    },
    {
      addr: '花巻市大迫町',
      isArea: false,
      pref: '岩手県',
      scale: 10,
    },
    {
      addr: '花巻市石鳥谷町',
      isArea: false,
      pref: '岩手県',
      scale: 10,
    },
    {
      addr: '花巻市東和町',
      isArea: false,
      pref: '岩手県',
      scale: 10,
    },
    {
      addr: '北上市柳原町',
      isArea: false,
      pref: '岩手県',
      scale: 10,
    },
    {
      addr: '遠野市青笹町',
      isArea: false,
      pref: '岩手県',
      scale: 10,
    },
    {
      addr: '一関市千厩町',
      isArea: false,
      pref: '岩手県',
      scale: 10,
    },
    {
      addr: '一関市室根町',
      isArea: false,
      pref: '岩手県',
      scale: 10,
    },
    {
      addr: '奥州市水沢大鐘町',
      isArea: false,
      pref: '岩手県',
      scale: 10,
    },
    {
      addr: '奥州市水沢佐倉河',
      isArea: false,
      pref: '岩手県',
      scale: 10,
    },
    {
      addr: '奥州市江刺',
      isArea: false,
      pref: '岩手県',
      scale: 10,
    },
    {
      addr: '奥州市胆沢',
      isArea: false,
      pref: '岩手県',
      scale: 10,
    },
    {
      addr: '登米市迫町',
      isArea: false,
      pref: '宮城県',
      scale: 20,
    },
    {
      addr: '登米市中田町',
      isArea: false,
      pref: '宮城県',
      scale: 10,
    },
    {
      addr: '登米市登米町',
      isArea: false,
      pref: '宮城県',
      scale: 10,
    },
    {
      addr: '登米市南方町',
      isArea: false,
      pref: '宮城県',
      scale: 10,
    },
    {
      addr: '登米市米山町',
      isArea: false,
      pref: '宮城県',
      scale: 10,
    },
    {
      addr: '気仙沼市赤岩',
      isArea: false,
      pref: '宮城県',
      scale: 10,
    },
    {
      addr: '気仙沼市笹が陣',
      isArea: false,
      pref: '宮城県',
      scale: 10,
    },
    {
      addr: '栗原市栗駒',
      isArea: false,
      pref: '宮城県',
      scale: 10,
    },
    {
      addr: '栗原市築館',
      isArea: false,
      pref: '宮城県',
      scale: 10,
    },
    {
      addr: '栗原市高清水',
      isArea: false,
      pref: '宮城県',
      scale: 10,
    },
    {
      addr: '栗原市若柳',
      isArea: false,
      pref: '宮城県',
      scale: 10,
    },
    {
      addr: '栗原市一迫',
      isArea: false,
      pref: '宮城県',
      scale: 10,
    },
    {
      addr: '大崎市古川三日町',
      isArea: false,
      pref: '宮城県',
      scale: 10,
    },
    {
      addr: '大崎市松山',
      isArea: false,
      pref: '宮城県',
      scale: 10,
    },
    {
      addr: '大崎市田尻',
      isArea: false,
      pref: '宮城県',
      scale: 10,
    },
    {
      addr: '宮城美里町木間塚',
      isArea: false,
      pref: '宮城県',
      scale: 10,
    },
    {
      addr: '角田市角田',
      isArea: false,
      pref: '宮城県',
      scale: 10,
    },
    {
      addr: '岩沼市桜',
      isArea: false,
      pref: '宮城県',
      scale: 10,
    },
    {
      addr: '丸森町鳥屋',
      isArea: false,
      pref: '宮城県',
      scale: 10,
    },
    {
      addr: '亘理町悠里',
      isArea: false,
      pref: '宮城県',
      scale: 10,
    },
    {
      addr: '仙台宮城野区苦竹',
      isArea: false,
      pref: '宮城県',
      scale: 10,
    },
    {
      addr: '石巻市大街道南',
      isArea: false,
      pref: '宮城県',
      scale: 10,
    },
    {
      addr: '石巻市相野谷',
      isArea: false,
      pref: '宮城県',
      scale: 10,
    },
    {
      addr: '石巻市前谷地',
      isArea: false,
      pref: '宮城県',
      scale: 10,
    },
    {
      addr: '石巻市桃生町',
      isArea: false,
      pref: '宮城県',
      scale: 10,
    },
    {
      addr: '東松島市矢本',
      isArea: false,
      pref: '宮城県',
      scale: 10,
    },
    {
      addr: '松島町高城',
      isArea: false,
      pref: '宮城県',
      scale: 10,
    },
    {
      addr: '利府町利府',
      isArea: false,
      pref: '宮城県',
      scale: 10,
    },
    {
      addr: '能代市上町',
      isArea: false,
      pref: '秋田県',
      scale: 10,
    },
    {
      addr: '三種町森岳',
      isArea: false,
      pref: '秋田県',
      scale: 10,
    },
    {
      addr: '大館市早口',
      isArea: false,
      pref: '秋田県',
      scale: 10,
    },
    {
      addr: '北秋田市新田目',
      isArea: false,
      pref: '秋田県',
      scale: 10,
    },
    {
      addr: '横手市大雄',
      isArea: false,
      pref: '秋田県',
      scale: 10,
    },
    {
      addr: '大仙市高梨',
      isArea: false,
      pref: '秋田県',
      scale: 10,
    },
    {
      addr: '白鷹町荒砥',
      isArea: false,
      pref: '山形県',
      scale: 10,
    },
  ],
  time: '2024/08/10 12:34:48.798',
  timestamp: {
    convert: '2024/08/10 12:34:48.79',
    register: '2024/08/10 12:34:48.798',
  },
  user_agent: 'jmaxml-seis-parser-go, relay, register-api',
  ver: '20231023',
};

export const tsunami = {
  areas: [
    {
      firstHeight: {
        arrivalTime: '2024/08/08 17:10:00',
      },
      grade: 'Watch',
      immediate: false,
      maxHeight: {
        description: '１ｍ',
        value: 1,
      },
      name: '愛媛県宇和海沿岸',
    },
    {
      firstHeight: {
        condition: '津波到達中と推測',
      },
      grade: 'Watch',
      immediate: true,
      maxHeight: {
        description: '１ｍ',
        value: 1,
      },
      name: '高知県',
    },
    {
      firstHeight: {
        condition: '津波到達中と推測',
      },
      grade: 'Watch',
      immediate: true,
      maxHeight: {
        description: '１ｍ',
        value: 1,
      },
      name: '大分県豊後水道沿岸',
    },
    {
      firstHeight: {
        condition: '津波到達中と推測',
      },
      grade: 'Watch',
      immediate: true,
      maxHeight: {
        description: '１ｍ',
        value: 1,
      },
      name: '宮崎県',
    },
    {
      firstHeight: {
        condition: '津波到達中と推測',
      },
      grade: 'Watch',
      immediate: true,
      maxHeight: {
        description: '１ｍ',
        value: 1,
      },
      name: '鹿児島県東部',
    },
    {
      firstHeight: {
        arrivalTime: '2024/08/08 17:00:00',
        condition: 'ただちに津波来襲と予測',
      },
      grade: 'Watch',
      immediate: true,
      maxHeight: {
        description: '１ｍ',
        value: 1,
      },
      name: '種子島・屋久島地方',
    },
  ],
  cancelled: false,
  code: 552,
  id: '66b4792ad616be440743d393',
  issue: {
    source: '気象庁',
    time: '2024/08/08 16:52:09',
    type: 'Focus',
  },
  time: '2024/08/08 16:52:10.336',
  timestamp: {
    convert: '2024/08/08 16:52:10.332',
    register: '2024/08/08 16:52:10.336',
  },
  user_agent: 'jmaxml-seis-parser-go, relay, register-api',
  ver: '20231023',
};

export const message = [message0, message1];
