name: Preview

on:
  push:
    branches: ["develop"]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: lint # Run only if the lint job succeeds
    if: github.repository == 'evacuate/evacuate' && github.ref == 'refs/heads/develop' # Run only if repository is evacuate/evacuate

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Dokku
        uses: dokku/github-action@v1.6.0
        with:
          git_remote_url: ssh://dokku@${{ secrets.DOKKU_PREVIEW_HOST }}:${{ secrets.DOKKU_PREVIEW_PORT }}/${{ secrets.DOKKU_PREVIEW_APP_NAME }}
          ssh_private_key: ${{ secrets.DOKKU_PREVIEW_SSH_PRIVATE_KEY }}
          branch: "develop"
          git_push_flags: --force
