name: Production

on:
  push:
    branches: ["main"]

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.18.x"

      - name: Install Dependencies
        run: npm install

      - name: Run Biome
        run: npm run lint

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: lint # Run only if the lint job succeeds

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Dokku
        uses: dokku/github-action@v1.5.0
        with:
          git_remote_url: ssh://dokku@${{ secrets.DOKKU_HOST }}:${{ secrets.DOKKU_PORT }}/${{ secrets.DOKKU_APP_NAME }}
          ssh_private_key: ${{ secrets.DOKKU_SSH_PRIVATE_KEY }}
          branch: "main"
          git_push_flags: --force
