name: Publish

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-push:
    name: Docker
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Extract version from tag
      - name: Extract version
        id: vars
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and tag the Docker image
      - name: Build Docker image
        run: |
          docker build \
            --tag ghcr.io/${{ github.repository }}:${{ env.VERSION }} \
            --tag ghcr.io/${{ github.repository }}:latest .

      # Push the Docker image to ghcr.io
      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}:${{ env.VERSION }}
          docker push ghcr.io/${{ github.repository }}:latest
