name: Service

on:
  push:
    branches: ["main", "develop"]

jobs:
  deploy-main:
    name: Production
    runs-on: ubuntu-latest
    if: github.repository == 'evacuate/evacuate' && github.ref == 'refs/heads/main' # Run only if repository is evacuate/evacuate and branch is main

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Dokku (Production)
        uses: dokku/github-action@v1.6.0
        with:
          git_remote_url: ssh://dokku@${{ secrets.DOKKU_HOST }}:${{ secrets.DOKKU_PORT }}/${{ secrets.DOKKU_APP_NAME }}
          ssh_private_key: ${{ secrets.DOKKU_SSH_PRIVATE_KEY }}
          branch: "main"
          git_push_flags: --force

  deploy-develop:
    name: Preview
    runs-on: ubuntu-latest
    if: github.repository == 'evacuate/evacuate' && github.ref == 'refs/heads/develop' # Run only if repository is evacuate/evacuate and branch is develop

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Dokku (Preview)
        uses: dokku/github-action@v1.6.0
        with:
          git_remote_url: ssh://dokku@${{ secrets.DOKKU_PREVIEW_HOST }}:${{ secrets.DOKKU_PREVIEW_PORT }}/${{ secrets.DOKKU_PREVIEW_APP_NAME }}
          ssh_private_key: ${{ secrets.DOKKU_PREVIEW_SSH_PRIVATE_KEY }}
          branch: "develop"
          git_push_flags: --force
