name: Sync to Develop Branch

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  sync-develop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Git identity
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Sync with develop branch
        run: |
          git fetch origin develop
          git checkout develop
          git reset --hard main
          git push -f
